name: "Publish ialarm-mqtt-dev"

env:
  ADDON_NAME: ialarm-mqtt-dev
  
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  publish:
    name: Publish Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: YAML Update Action
        uses: fjogeleit/yaml-update-action@v0.12.2
        with:
          valueFile: 'ialarm-mqtt-dev/config.yaml'
          propertyPath: 'version'
          value: 0.11.1-dev-${{ github.sha }}
          message: "Updated ialarm-mqtt-dev/config.yaml version"
          commitChange: true
          branch: dev
          #targetBranch: master
          #createPR: 'true'        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ${{ env.ADDON_NAME }} \
            --docker-user maxill1 \
            --docker-hub maxill1