name: "Publish ialarm-mqtt-dev"

env:
  ADDON_NAME: ialarm-mqtt-dev
  
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  publish:
    name: Publish Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}        
      - name: YAML Update Action
        uses: fjogeleit/yaml-update-action@v0.12.2
        with:
          valueFile: 'ialarm-mqtt-dev/config.yaml'
          propertyPath: 'version'
          value: dev-${{ steps.vars.outputs.sha_short }}
          message: "Updated ialarm-mqtt-dev/config.yaml version to ${{ steps.vars.outputs.sha_short }}"
          commitChange: true
          branch: dev
          targetBranch: master
          createPR: 'true'              
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target ${{ env.ADDON_NAME }} \
            --docker-user stfncntr \
            --docker-hub stfncntr